version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./notes-api/init-db:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: ./notes-api
    container_name: notes_api_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/notesdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./notes-vue
    container_name: notes_vue_app
    depends_on:
      - backend
    ports:
      - "8181:80"
  
  db-seed:
    image: mysql:8.0
    container_name: mysql_db_seed
    depends_on:
      - db
    volumes:
      - ./notes-api/init-db:/init-db:ro
    entrypoint: ["sh","-c","\n      echo 'Waiting for DB to be ready...';\n      until mysql -h db -P 3306 -uuser -ppassword -e \"SELECT 1\" >/dev/null 2>&1; do\n        sleep 1;\n      done;\n      echo 'DB ready â€” importing init-db/init.sql';\n      mysql -h db -P 3306 -uuser -ppassword notesdb < /init-db/init.sql;\n      echo 'Seed complete';\n      exit 0\n    "]

volumes:
  mysql_data:
